name: Lint workflow

on:
  pull_request:
    branches: 
      - develop
      - staging
    
jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 21.x

      - name: install deps
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run test
        run: npm run test
